### ISSUE TITLE
http proxy authentication support for download 

### ISSUE THREAD

**Issue by tolot27** [pcingola/SnpEff#153]
Issue #148 is marked as solved because one can provide proxy settings via java args (i. e. `java -Djava.net.useSystemProxies=true`). While this is true in general, it does not work for proxies requiring authentication.  This must be separately supported by the java application for instance via a custom default `Authenticator`. See [Java: process http.proxyUser and http.proxyPassword](http://rolandtapken.de/blog/2012-04/java-process-httpproxyuser-and-httpproxypassword) for an example.

**Comment by pcingola** [comment]
It is true that authentication proxy is not supported, I don't see this as a critical feature since: a) there is no large user base suffering from this problem; and b) as mentioned in #148, you can always use curl / wget from the command line.

At the moment I'll close this issue because it doesn't seem to be critical, but if you'd like to contribute the code, please go ahead and re-open it.
