### ISSUE TITLE
tRNAs

### ISSUE THREAD

**Issue by ptmcgrat** [pcingola/SnpEff#213]
Looking over the output of a custom database, it looks like tRNAs are being treated as protein coding genes. 

In the BioType.java file, it appears that this is how they are handled. Is this correct? Is there a reason to handle trna as protein_coding genes?

```
				switch (str.toLowerCase()) {
				case "mrna":
				case "protein":
				case "cds":
				case "trna":
				case "start_codon":
				case "stop_codon":
				case "five_prime_utr":
				case "5'-utr":
				case "5'utr":
				case "5utr":
				case "three_prime_utr":
				case "3'-utr":
				case "3'utr":
				case "3utr":
					return protein_coding;
```

**Comment by stephlo76** [comment]
I see the same behavior here. Using a gff file for annotation where tRNAs have "gene", "tRNA", and "exon" entries but (as it should be) no "CDS" entries. Anyway, snpEff output shows "protein_coding" and lists changed amino acids. Version 4.3u

**Comment by pcingola** [comment]
Closing old issues.

**Comment by AlexanderThomasJulian** [comment]
I know this has marked as closed, but this issue still seems to be present.

When trying to build a database for the NCBI accession GCA_024399295.1, the protein check fails because 46 proteins could not be found in my protein.fa file. When running with the -d flag, I see that these 46 "proteins" are in fact tRNA genes in my GTF. I think the above handling of tRNA is causing the problem, as it is looking for a protein sequence that just doesn't exist...
