### ISSUE TITLE
dbNSFP_genelevel

### ISSUE THREAD

**Issue by MartaRus** [pcingola/SnpEff#224]
Hi everyone
can someone help me to annotate my vcf with the database dbNSFP_gene? I cannot find the right command.  It is a database extracted from the dbNSFP that should annotate at gene-level (instead of variant level).

Thank you

**Comment by kevinblighe** [comment]
Answer posted on Biostars: https://www.biostars.org/p/378876/#379262

**Comment by berntpopp** [comment]
> Answer posted on Biostars: https://www.biostars.org/p/378876/#379262

Sorry Kevin, but your answer on biostars is either not up-to-date (maybe because the link you posted got updated) or does not answer this question. Can you please update your solution if you have one?

**Comment by pcingola** [comment]
Closing old issues.

**Comment by valleema** [comment]
Hello @pcingola and @kevinblighe ,

I found this issue, and I have the same problem. The answer on biostars and the links provided are not helping because:

- the link to http://snpeff.sourceforge.net/SnpSift.html#dbNSFP is re-routing to https://pcingola.github.io/SnpEff/ homepage. Even browsing it through the [web archive latest snapshots](https://web.archive.org/web/20180526040844/http://snpeff.sourceforge.net/SnpSift.html#dbNSFP) I cannot find "an example of how you can prepare the __gene_ file for use" as @kevinblighe said.
- the second link https://www.dnastar.com/blog/resources/dbnsfp-gene-level-annotations/ where @kevinblighe proposes to download ("__gene_ file can be directly downloaded from other sources") is not useful because it is the same file included in the official dbNSFP zip.

Of course, trying to annotate using the __gene_ database with the `SnpSift.jar dbnsfp` command fails, as the database is constructed like this (first 10 lines, first 10 columns):
```shell
$ zcat dbNSFP4.1_gene.complete.gz | head | cut -f-10
Gene_name       Ensembl_gene    chr     Gene_old_names  Gene_other_names        Uniprot_acc(HGNC/Uniprot)       Uniprot_id(HGNC/Uniprot)        Entrez_gene_id  CCDS_id Refseq_id
A1BG    ENSG00000121410 19      .       .       P04217  A1BG_HUMAN      1       CCDS12976       NM_130786
A1BG-AS1        ENSG00000268895 19      NCRNA00181;A1BGAS;A1BG-AS       FLJ23569        .       .       503538  .       NR_015380
A1CF    ENSG00000148584 10      .       ACF;ASP;ACF64;ACF65;APOBEC1CF   Q9NQ94  A1CF_HUMAN      29974   CCDS7241;CCDS7242;CCDS7243;CCDS73133    NM_001198818;NM_014576
A2M     ENSG00000175899 12      .       FWP007;S863-7;CPAMD5    P01023  A2MG_HUMAN      2       CCDS44827       NM_000014
A2M-AS1 ENSG00000245105 12      .       .       .       .       144571  .       NR_026971
A2ML1   ENSG00000166535 12      CPAMD9  FLJ25179;p170   A8K2U0  A2ML1_HUMAN     144568  CCDS8596;CCDS73439      NM_001282424;NM_144670
A2ML1-AS1       ENSG00000256661 12      .       .       .       .       100874108       .       .
A2ML1-AS2       ENSG00000256904 12      .       .       .       .       106478979       .       .
A2MP1   ENSG00000256069 12      A2MP    .       .       .       3       .       NG_001067;NR_040112
```

**Comment by kevinblighe** [comment]
Thanks to all for the comments. I moved my Biostars answer back to a comment and added a note.

I will leave it to the developer(s0 to address this issue

**Comment by valleema** [comment]
Thanks, I hope dev(s) will help. Or I will merge the fields with Unix tools, based on Ensembl IDs, but it will duplicate the data a lot...
