### ISSUE TITLE
SnpEff VCF filtering

### ISSUE THREAD

**Issue by Xavster838** [pcingola/SnpEff#257]
Great tool, however I am wondering how filtering of the VCF file works when running SnpEff. 

1. VERSION: I am running snpEff version 5.0 in a conda environment
2. COMMAND: I run snpEff with the following command
`snpEff -c ./snpEff.config <database name> ../<my_vcf.vcf>  > all.vcf.anno_now.vcf`
3. DATA: 
- The Database is made from hg38 fasta and associated gencode gff 
- VCF file with 39 samples and 193,330 high quality variants (Mapping Quality = 60)
5. output: VCF file annotated at 1523 variants (1523 variants recieve "ANN" column info column )

How does the program filter these variants?

**Comment by pcingola** [comment]
A few comments:
1. You don't need to build the database for hg38, it is available for download: `java -jar snpEff.jar download -v hg38`
2. I'm not sure what you'd like to filter (if you'd like to filter variants, use SnpSift instead of SnpEff)
3. If you'd like to filter annotations created by SnpEff, use a `-h` command line to show the available options.
