### ISSUE TITLE
Filtering samples instead of sites

### ISSUE THREAD

**Issue by shbrainard** [pcingola/SnpEff#292]
I would like to filter out samples (i.e., individuals) based on comparisons made across all sites (i.e., genotyped loci).  Reading the manual, it would seem I could do this with the `filter` command, but the following code removes sites, instead of genotypes with DP < 10

```
grep \#CHROM unfiltered.vcf | tr -dc : | wc -c #672 (all samples have a colon in their ID)
wc -l unfiltered.vcf #10000
cat unfiltered.vcf | java -jar $SnpSift filter " ( GEN[*].DP[*] > 10 )" > filtered.vcf
grep \#CHROM filtered.vcf | tr -dc : | wc -c # still 672
wc -l filtered.vcf #9435 # low depth sites seem to have been deleted.
```

Relatedly, my assumption was that this filter would remove samples with DP < 10 at any site.  I would also like to perform thresholding using average DP -- i.e., the mean DP per sample averaged across all sites.  Please let me know if this is possible, as I didn't see it mentioned in the manual here: https://pcingola.github.io/SnpEff/ss_filter/

Thanks!

**Comment by pcingola** [comment]
SnpSift is focused on filtering variants (VCF lines) instead of samples (VCF columns).

This is certainly not a common practice in sequencing data analysis, since due to coverage variance you'll almost certainly can find a position in the genome with low coverage in every sample. Thus a filtering strategy like the one you propose will most likely end up eliminating all samples from the VCF.
