### ISSUE TITLE
Replacing akka calls with java.util.concurrent for multithreading

### ISSUE THREAD

**Issue by pgrt** [pcingola/SnpEff#309]
Hi,

While doing the Debian packaging of the last tagged version (4.3t), I wrote some lines to use java.util.concurrent instead of akka.actor.

I did some tests, e.g. by doing simple annotations with the -t parameter, and it seems to work well. Please find my patch enclosed, and feel free to consider it or not.

Best,
Pierre

[replacing_akka_with_java_util_concurrent.txt](https://github.com/pcingola/SnpEff/files/6229537/replacing_akka_with_java_util_concurrent.txt)

**Comment by pcingola** [comment]
Hi, thank you for your code. I'll try to review it soon.

The "main" change between versions 4.3 and 5.0, is related to downloading
databases, so your code will still be applicable for version 5.0.

Please note the version 4.3 is will no longer work due to these download changes.
The reason being that all SnpEff databases have been moved from SourceForge
to Azure (Microsoft kindly offered to host them as there were some limitations
on the size/number of files I could host on SourceForge). So as of version 5.0 the
download code has been changed to handle Azure blobs. 

I've also been working on changing the Scala Akka library to native Java parallel
streams, which I was hoping to finish and release in April. In any case, your code
will definitely help me to remove akka and use a native java approach.
Thank you!!!

**Comment by pgrt** [comment]
Hi,

Thanks! I will be very happy if you can proofread this code -- and of course, make any change that would be profitable.

I understand from your response that versions 4.3* should not be working in a close future. Does this milestone correspond with an official release of a version 5.* ?

Thank you and have a good day,
Pierre

**Comment by pcingola** [comment]
Hi Pierre,
  Version 4.3 can only download old (potentially obsolete) databases since
version 5.0 was released in late 2020. I would not recommend using or
installing v4.3.
  I hope this clarifies.

    Pablo

**Comment by antonylebechec** [comment]
Hi Pablo!

Thanks for this new release 5.0!

I would like to know if it's possible to obtain a specific URL for this new release (e.g. https://snpeff.blob.core.windows.net/versions/snpEff_5.0e_core.zip, with a pattern like snpEff_<version>_core.zip), instead of, or in addition to, a "latest" URL (https://snpeff.blob.core.windows.net/versions/snpEff_latest_core.zip).
In order to clearly trace my tools deployment, I need to be sure that I download the chosen version (and to trace databases release to).

Thanks a lot!

Best,
Antony
