### ISSUE TITLE
GRCh38 latest version

### ISSUE THREAD

**Issue by estyholt** [pcingola/SnpEff#317]
Hi,

By running `snpEff databases `
It looks like there are only GRCh38.99 / GRCh38.p7.RefSeq versions available for Human GRCh38.
If I would like to use, say, the newest version = GRCh38.103 - Do I need to go through the long process of building a database?

The reason why I need that specific one is because I have a list of tricky genes with major changes between versions....

**Comment by pcingola** [comment]
I was going to rebuild all ENSEMBL databases when they release version 104, which is expected these days (https://www.ensembl.info/category/01-release/). Mostly because it has the new MANE release transcript set.

I'm also planning to add new annotation features for that release (those will be human genome only).

Does that sound OK?

**Comment by estyholt** [comment]
@pcingola - this will be amazing! 

But if I want a very very specific version (GRCh38.98) - Will I need to go through the long process of building a database?

Thank you for the prompt reply

**Comment by estyholt** [comment]
@pcingola - now that version 104 has been released - when do you think you will rebuild all ENSEMBL databases?
Thank you

**Comment by pcingola** [comment]
Yes, I'll try to do it soon. I'm finishing some updates.

**Comment by pjhop** [comment]
@pcingola I was wondering whether databases for any of the latest Human GRCh38 ensembl versions (104/105) are already available? (it seems that GRCh38.99 is the latest version available)

Thanks for all the great work!
