### ISSUE TITLE
log4j2 vulnerability

### ISSUE THREAD

**Issue by bethrusnak** [pcingola/SnpEff#364]
My scans are showing that snpEff.jar is vulnerable to the Log4j2 exploit. Do you know when this might be fixed?

**Comment by pcingola** [comment]
SnpEff uses Log4j 1.2.15 which is not vulnerable to this security thread. See [refernce here](https://www.cisa.gov/uscert/apache-log4j-vulnerability-guidance)

Even if SnpEff was vulnerable, which according to my understanding is not, SnpEff doesn't run as a server. Thus it would not allow uses who don't already have access to gain access by exploiting such vulnerability.

Overall, I don't see the need to update SnpEff / SnpSift since they are not vulnerable, but let me know if you think I'm mistaken.

**Comment by pcingola** [comment]
I'll try to update soon if it makes your life easier.

**Comment by bethrusnak** [comment]
Thanks - might help for everyone. Seems like this risk is the gift that keeps on giving. :-(

**Comment by bethrusnak** [comment]
Thanks for updating!
