### ISSUE TITLE
Missing some images in output snpEff_summary.html file.

### ISSUE THREAD

**Issue by jhxaz** [pcingola/SnpEff#375]
**Describe the issue**
Missing some images in output snpEff_summary.html file.

![image](https://user-images.githubusercontent.com/41499820/151550100-56bf5b81-c31e-45d2-89c5-dab2227376c5.png)!
![image](https://user-images.githubusercontent.com/41499820/151550402-64ef4c5a-8cc0-4424-8322-a9258f2dd9e0.png)

**To Reproduce**
1. SnpEff version: 5.1
2. Genome version: hg19
3. SnpEff full command line: 
```
nohup java -Xmx16g \
-jar  /mnt/memory2/database/SoftWare/snpEff/snpEff.jar \
-v hg19 \
./examples/test.chr22.ann.vcf \
-s test.chr22.ann_summary.html \
>./test.chr22_Anno.vcf \
2>test.chr22.Anno.log2 &
```

4. Output / Error message: Please include detailed infomration, such as transcript ID, VCF line output, etc.

No error reported.

**Expected behavior**
![image](https://user-images.githubusercontent.com/41499820/151550251-8bf62543-5f7e-4d09-8d99-55ba1e393629.png)

When I compared the standard output of snpEff_summary.html with mine, I  surprisedly found some images missed, it seems they are  
not successfully loaded.  For examples, the bar plot of  % variations in different gene features, and the position of variations . I want to know what is wrong and how to solve it. In addition,  can I get the stats source data of snpEff_summary.html  and plots the figures by myself use R ?

**Data**

Test data of SnpEff version: 5.1.

**Comment by DrownedMala** [comment]
Hi there, I'm having the same issue, did you manage to solve it?

**Comment by 5katerina** [comment]
Hi, I have the same problem, have you solved it?

**Comment by DrownedMala** [comment]
Unfortunately, I have not

**Comment by ethering** [comment]
I know this issue is marked as closed, but it hasn't been resolved.
I'm getting the same problem as the OP, i.e. plots not displaying in the summary.html file (the same plots as the OP). I've looked further into this.
In the source file GoogleHistogram.java it states that the plots are made using 'A simple wrapper to goolge charts API (from charts4j)'
charts4j (https://code.google.com/archive/p/charts4j/) says that it enables developers to programmatically create the charts available in the Google Chart Tools API (https://developers.google.com/chart/image/docs/gallery/chart_gall)
The images that don't display are all embedded URLs, linked to http://chart.apis.google.com
If I copy and paste one of the links into my web browser I get "The requested URL /chart was not found on this server."
According to this page: https://en.wikipedia.org/wiki/Google_Chart_API, the Google Chart API  is deprecated and the server was turned off on March 18, 2019.
Is it possible that the plots are using a deprecated server?
