### ISSUE TITLE
Database build request - UM_Priviv_1.0

### ISSUE THREAD

**Issue by rac266** [pcingola/SnpEff#418]
Hello,
I have been running into issues building a database for my genome UM_Priviv_1.0. It fails at the cds and protein check due to differences in FASTA file transcript IDs compared to the database's transcript's IDs. Any assistance or advice on this is greatly appreciated! The RefSeq assembly files can be found below:

https://www.ncbi.nlm.nih.gov/assembly/GCF_022837055.1

sequences.fa: [GCF_022837055.1_UM_Priviv_1.0_genomic.fna.gz](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/022/837/055/GCF_022837055.1_UM_Priviv_1.0/GCF_022837055.1_UM_Priviv_1.0_genomic.fna.gz)

genes.gtf: [GCF_022837055.1_UM_Priviv_1.0_genomic.gtf.gz](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/022/837/055/GCF_022837055.1_UM_Priviv_1.0/GCF_022837055.1_UM_Priviv_1.0_genomic.gtf.gz)

protein.fa: [GCF_022837055.1_UM_Priviv_1.0_protein.faa.gz](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/022/837/055/GCF_022837055.1_UM_Priviv_1.0/GCF_022837055.1_UM_Priviv_1.0_protein.faa.gz)

cds.fa: [GCF_022837055.1_UM_Priviv_1.0_cds_from_genomic.fna.gz](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/022/837/055/GCF_022837055.1_UM_Priviv_1.0/GCF_022837055.1_UM_Priviv_1.0_cds_from_genomic.fna.gz)

Thank you for your time and assistance with this issue!

**Comment by pcingola** [comment]
The CDS / protein FASTA headers should match the transcriptID
Here is the related documentation: http://pcingola.github.io/SnpEff/se_build_db/#step-3-checking-the-database

Since that is not the case in your files, you may need to convert the FASTA files to add/change the header information.
You may need to join information from `protein_id` which seems to be in both the GTF and the FASTA
