### ISSUE TITLE
Invalid HGVSc annotation question

### ISSUE THREAD

**Issue by seoung-chul** [pcingola/SnpEff#423]
1. SnpEff version: 5.1d
2. Genome version: hg19
3. SnpEff full command line:  java -Xmx8g -jar snpEff.jar hg19 input/test.vcf > output/snpeff_test.vcf

Hi
I annotated the following mutations using SnpEff. 

[VCF]
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	test
17	41277393	.	G	A	8752.64	.	AC=1;AF=0.5;AN=2;BaseQRankSum=-3.96;DP=909;ExcessHet=3.0103;FS=0;MLEAC=1;MLEAF=0.5;MQ=60;MQRankSum=0;QD=9.93;ReadPosRankSum=0.825;SOR=0.724	GT:AD:DP:GQ:PL	0/1:428,453:881:99:8760,0,9156

However, it seems that the HGVSc of Transcript NM_007294.4 is wrong.
In SNPEff, c.-125C>T was obtained in NM_007294.4, but in fact, c.-125C>T is HGVSc of NM_007294.3, not NM_007294.4.
I wonder if I made the wrong annotation in SnpEff.

**Comment by pcingola** [comment]
I'm not sure what you mean. I'd like to ask a few questions to see if I can better understand the issue and possibly replicate the error condition/bug:

- What do you mean by "Transcript NM_007294.4 is wrong"? 
- Do you mean that the transcript has that annotation you expect in NM_007294.4 is different than c.-125C>T?
- Can you clarify which annotation you expect for that variant in NM_007294.4 as opposed to NM_007294.3?

Thank you for your help!

**Comment by toddajohnson** [comment]
I just checked that position in UCSC Genome Browser and would hazard a guess that seoung-chul's concern comes from that position residing outside the boundaries of NM_007294.4, whereas it was inside the 5'-UTR of the previous reference sequence version NM_007294.3.  For NM_007294.4, shouldn't the variant be considered "transcript flanking" and not annotated?

**Comment by pcingola** [comment]
![Screen Shot 2022-08-18 at 8 52 51 AM](https://user-images.githubusercontent.com/1334427/185399472-cfbfe04f-03f8-42e2-860c-6dfa4b3a21ce.png)

This is a screenshot from UCSC's genome browser.
The red vertical line indicates where the variant is located.

The annotation I get is:
```
A|upstream_gene_variant|MODIFIER|BRCA1|BRCA1|transcript|NM_007294.4|protein_coding||c.-125C>T|||||12|
```

It seems like "upstream_gene_variant" is a correct annotation since it's upstream of NM_007294.4.
Am I misinterpreting your comment?


Upstream and Downstream are defined (rather arbitrarily) as 5Kb outside the gene/transcript.
You can set it to another number using the `-ud` command line argument. If you do `-ud 0`, then you won't get any upstream/downstream annotations.

**Comment by toddajohnson** [comment]
I don’t see a problem with annotating the variant as “upstream_gene_variant”, but I think the original poster’s question was whether the HGVS.c field should be annotated for that variant as “c.-125C>T” for the specific reference sequence NM_07294.4, or whether the HGVS.c field should be empty.  The HGVS page on variant numbering (http://varnomen.hgvs.org/bg-material/numbering/) has under the “transcript flanking” section, “it is not allowed to describe variants in nucleotides beyond the boundaries of the reference sequence using the reference sequence”, and based on the browser plot, that variant is outside that reference sequence.  It also mentions “suggestions made to extend the recommendations for nucleotide numbering of coding DNA reference sequences to specifically mark non-transcribed nucleotides have been made but were rejected” with a link to “Open issues” (http://varnomen.hgvs.org/recommendations/open-issues/), so obviously, there have been questions about that situation in the past.  Strangely, based on that rule, all of the NCBI RefSeq transcripts would appear to necessitate a blank HGVS.c field for that variant, but there are several Ensembl splice variants that would include the variant in their reference sequence.  Maybe, the snpEff manual could mention that while using the HGVS notation, the annotation does not strictly adhere to HGVS’ conventions?

From: Pablo Cingolani ***@***.***>
Reply-To: pcingola/SnpEff ***@***.***>
Date: Thursday, August 18, 2022 at 10:04 PM
To: pcingola/SnpEff ***@***.***>
Cc: "Todd A. Johnson" ***@***.***>, Comment ***@***.***>
Subject: Re: [pcingola/SnpEff] Invalid HGVSc annotation question (Issue #423)


[Screen Shot 2022-08-18 at 8 52 51 AM]<https://user-images.githubusercontent.com/1334427/185399472-cfbfe04f-03f8-42e2-860c-6dfa4b3a21ce.png>

This is a screenshot from UCSC's genome browser.
The red vertical line indicates where the variant is located.

The annotation I get is:

A|upstream_gene_variant|MODIFIER|BRCA1|BRCA1|transcript|NM_007294.4|protein_coding||c.-125C>T|||||12|

It seems like "upstream_gene_variant" is a correct annotation since it's upstream of NM_007294.4.
Am I misinterpreting your comment?

Upstream and Downstream are defined (rather arbitrarily) as 5Kb outside the gene/transcript.
You can set it to another number using the -ud command line argument. If you do -ud 0, then you won't get any upstream/downstream annotations.

**Comment by pcingola** [comment]
Thank you @toddajohnson for the detailed explanations and references to HGSV.c
Now I finally understand what you mean and why.

It looks like this part of the notation changed since I implemented it, which is not surprising since I implemented this a long time ago.

I'll take a detailed look at the HGSV links you've sent and see if I can change the implementation accordingly.

Thank you!
