### ISSUE TITLE
Why bacteria genome has predicted intron/exon regions? 

### ISSUE THREAD

**Issue by elifozcelik** [pcingola/SnpEff#506]
**Describe the issue**
In my analysis, I use E. coli and should not be seeing any exon or intron regions since this is a bacteria. How does this snpEffectPredictor work?

**To Reproduce**
1. SnpEff version: conda install -c bioconda snpeff (version 5.0)
2. Genome version: snpEff Escherichia_coli_str_k_12_substr_mg1655
3. SnpEff full command line: snpEff Escherichia_coli_str_k_12_substr_mg1655 filtered_a10.vcf > snpEff_a10.vcf
4. I am attaching my HTML file's screen shot. 

<img width="1028" alt="Screenshot 2023-11-02 at 10 44 32 AM" src="https://github.com/pcingola/SnpEff/assets/72396952/87cbbeac-6263-44e8-b02c-3e3eac3ccc77">

**Comment by elifozcelik** [comment]
How do you predict the region effects?

**Comment by elifozcelik** [comment]
How do you predict regional effects? using gtf?

**Comment by pcingola** [comment]
Closing old issues. Feel free to re-open if it was not solved on your side.

I could not reproduce the issue, since I don't have the `filtered_a10.vcf` file.
Tip to debug: In a nutshell, if you could isolate the variant causing this and attach it to the incident (e..g `grep -i intron` on the output VCF file).

> How do you predict regional effects? using gtf?

You can see the details here: https://pcingola.github.io/SnpEff/snpeff/outputsummary/#annotations-region

I hope this helps
