### ISSUE TITLE
Provide consistent download targets

### ISSUE THREAD

**Issue by chapmanb** [pcingola/SnpEff#70]
Pablo;
Would it be possible to have consistent download targets for the sub-releases within a version (4.1, 4.1a...)? With the current update in place approach, downstream installs that depend on a consistent download will break (Homebrew/homebrew-science#1708). If we could point to a fixed sub-release that remains consistent, this would be a big help and allow migrations based on releases. Thanks much.

**Comment by pcingola** [comment]
Hi Brad,
  I was not aware that downstream packages were were 
checksumming snpEff_v*_core.zip files. You are right that this 
is a bad practice. This is done because SourceForge asked me to
reduce the disk space and number of files I was using in their 
servers.
  I'll try to keep a more consistent versioning from now (if they 
complain again, I'll have to remove older versions though).
   Apologies for the inconvenience.

       Pablo

**Comment by chapmanb** [comment]
Pablo;
Thanks much for this, it will be a big help. It's toally understood about space with sub-version issues. I thought sourceforge would be giving you a bit of a hard time with all of the databases you provide. We mainly just need a bit of transition time to move between the sub-releases so don't need all of the previous versions kept indefinitely, but having a stable target to avoid breaking when you upload it is a big help. Thank you again for all the work on snpEff.
